version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: taskmanager-db
    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_pass
      POSTGRES_DB: fastapi_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal

  backend:
    build: ./back
    container_name: taskmanager-api
    restart: always
    env_file:
      - ./taskmanagerback/.env
    depends_on:
      - db
    networks:
      - internal
    ports:
      - "8000:8000"

  frontend:
    build: ./taskmanagerfront
    container_name: taskmanager-frontend
    restart: always
    networks:
      - internal
    ports:
      - "3000:80"   

volumes:
  db_data:

networks:
  internal:
