sonar.projectKey=romanlafi_TaskManager-App
sonar.organization=romanlafi

sonar.sources=taskmanagerfront/src,cloudflare/src,packages/types
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info